Source/Net1711_231_5_InternManagement/InternManagementWebApp/Controllers/InternProfilesController.cs
using Microsoft.AspNetCore.Mvc;
using InternManagementData.Models;
using Newtonsoft.Json;
using System.Text;
using InternManagementData.DTO;
using System.ComponentModel;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using System.Net.Http;
using NuGet.Common;
using System.Net.Http.Headers;

namespace InternManagementWebApp.Controllers
{
    public class InternProfilesController : Controller
    {
        private string apiUrl = "https://localhost:7038/api/Intern/";
        public InternProfilesController()
        {
        }
        public IActionResult index()
        {
            string token = HttpContext.Session.GetString("accessToken");
            if(token == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpGet]
        public async Task<List<InternProfile>> GetAll()
        {
            try
            {
                var result = new List<InternProfile>();
                using (var httpClient = new HttpClient())
                {
                    string token = HttpContext.Session.GetString("accessToken");
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                    using (var response = await httpClient.GetAsync(apiUrl + "GetAll"))
                    {
                        if (response.IsSuccessStatusCode)
                        {
                            var content = await response.Content.ReadAsStringAsync();
                            result = JsonConvert.DeserializeObject<List<InternProfile>>(content);
                        }
                    }
                }
                return result;
            } catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
        
        [HttpGet]
        public IActionResult Create()
        {
            try
            {
                return PartialView("_add", new InternProfileDTO());
            } catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                using (var httpClient = new HttpClient())
                using (var response = await httpClient.GetAsync(apiUrl + "GetById?code=" + id))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        var content = await response.Content.ReadAsStringAsync();

                        var result = JsonConvert.DeserializeObject<InternProfile>(content);
                          return PartialView("_edit", new InternProfileDTO { InternAddress =  result.InternAddress,
                          InternEmail = result.InternEmail,
                          InternID = result.InternId,
                          InternName = result.InternName,
                          InternPhone = result.InternPhone,
                          Major = result.Major,
                          University = result.University});
                    }
                    throw new Exception("id is not exits");
                }

              
            }
            catch (Exception ex)
            {
                // Log the exception
                // LogError(ex);
                return BadRequest("An error occurred while loading the form.");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Save(InternProfileDTO profileDTO)
        {

            try
            {
                var payload = new
                {
                    InternID = profileDTO.InternID,
                    InternName = profileDTO.InternName,
                    InternAddress = profileDTO.InternAddress,
                    InternEmail = profileDTO.InternEmail,
                    InternPhone = profileDTO.InternPhone,
                    University = profileDTO.University,
                    Major = profileDTO.Major
                };


                var jsonPayload = JsonConvert.SerializeObject(payload);
                var content = new StringContent(jsonPayload, Encoding.UTF8, "application/json");

                var result = new List<InternProfile>();
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.PostAsync(apiUrl + "Create", content))
                    {
                        if (response.IsSuccessStatusCode)
                        {
                            return Json(new { status = 1, message = "Intern profile created successfully." });

                        }
                    }
                }
                return Json(new { status = 0, message = "Failed to create intern profile: " });

            }
            catch (Exception ex)
            {
                return Json(new { status = 0, message = "Failed to create intern profile: " + ex });
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(InternProfileDTO profileDTO)
        {

            try
            {
                var payload = new
                {
                    InternID = profileDTO.InternID,
                    InternName = profileDTO.InternName,
                    InternAddress = profileDTO.InternAddress,
                    InternEmail = profileDTO.InternEmail,
                    InternPhone = profileDTO.InternPhone,
                    University = profileDTO.University,
                    Major = profileDTO.Major
                };


                var jsonPayload = JsonConvert.SerializeObject(payload);
                var content = new StringContent(jsonPayload, Encoding.UTF8, "application/json");

                var result = new List<InternProfile>();
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.PutAsync(apiUrl + "Update", content))
                    {
                        if (response.IsSuccessStatusCode)
                        {
                            return Json(new { status = 1, message = "Intern profile Updated successfully." });

                        }
                    }
                }
                return Json(new { status = 0, message = "Failed to update intern profile: " });

            }
            catch (Exception ex)
            {
                return Json(new { status = 0, message = "Failed to update intern profile: " + ex });
            }
        }
        [HttpDelete]
        public async Task<string> Delete(int id)
        {
            try
            {
                string? result = null;
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.DeleteAsync(apiUrl + "Remove?profileid=" + id))
                    {
                        if (response.IsSuccessStatusCode)
                        {

                            result = "Delete Successful";
                        }else
                        {
                            result = "Can not Delete";
                        }
                        
                    }
                }
                return result;
            } catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
    }
}

Source/Net1711_231_5_InternManagement/InternManagementWebApp/Views/InternProfiles/Index.cshtml
@model IEnumerable<InternManagementData.Models.InternProfile>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<div class="row">
    <div class="col-md-10">
        <h3 class="display-8">TopUp List</h3>
    </div>
    <div class="col-md-2 text-end">
        <button type="button" class="btn btn-primary" onclick="add();">
            Add
        </button>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr class="card-header">
                    <th class="card-title text-center">Id</th>
                    <th class="card-title text-center">Name</th>
                    <th class="card-title text-center">Address</th>
                    <th class="card-title text-center">Email</th>
                    <th class="card-title text-center">Phone</th>
                    <th class="card-title text-center">University</th>
                    <th class="card-title text-center">Major</th>
                    <th class="card-title text-center">MentorID</th>
                    <th class="card-title text-center"></th>
                </tr>
            </thead>
            <tbody class="tblInterns">
            </tbody>
        </table>
    </div>
</div>

<div class="modal fade" id="internModal" tabindex="-1" aria-labelledby="internModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            @using (Html.BeginForm(null, null, FormMethod.Post, new { name = "frm", id = "frm" }))
            {
                @Html.AntiForgeryToken()
                <div class="modal-header">
                    <h5 class="modal-title" id="internModalLabel">TopUp Transaction</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div id="internModalContent"></div>
                </div>
                <div class="modal-footer">
                    <button id="btSave" type="button" class="btn btn-primary">Save</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            }
        </div>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        $(document).ready(
            function () {
            loadData();

            $("#btSave").click(function () {
                var formData = new FormData();
                    formData.append("InternID", $("#InternID").val());

                    formData.append("InternName", $("#InternName").val());
                    formData.append("InternAddress", $("#InternAddress").val());
                    formData.append("InternEmail", $("#InternEmail").val());
                    formData.append("InternPhone", $("#InternPhone").val());
                    formData.append("University", $("#University").val());
                    formData.append("Major", $("#Major").val());
                  


                console.log(formData);
                var type = $('#Type').val();

                    if (type == "edit") {

                        $.ajax({
                            type: 'POST',
                            url: '@Url.Action("Edit", "InternProfiles")',
                            //contentType: 'application/json;charset=utf-8',
                            //dataType: "json",
                            processData: false,
                            contentType: false,
                            data: formData,
                            success: function (result) {
                                //console.log(result);

                                if (result.status >= 1) {
                                    $('#internModal').modal('hide');
                                    loadData();
                                }
                                // alert(result.message);
                            },
                            error: function (xhr, error) {
                                //alert(xhr.responseText);
                                console.log(xhr);
                            }
                        });
                }


                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("Save", "InternProfiles")',
                    //contentType: 'application/json;charset=utf-8',
                    //dataType: "json",
                    processData: false,
                    contentType: false,
                    data: formData,
                    success: function (result) {
                        //console.log(result);

                        if (result.status >= 1) {
                                $('#internModal').modal('hide');
                            loadData();
                        }
                       // alert(result.message);
                    },
                    error: function (xhr, error) {
                        //alert(xhr.responseText);
                        console.log(xhr);
                    }
                });
            });

            ////////
        });

        function loadData() {
            $.ajax({
                url: '@Url.Action("GetAll", "InternProfiles")',
                type: "GET",
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                success: function (result) {
                    var html = '';
                    $.each(result, function (key, item) {
                        //console.log(item);
                        html += '<tr>';
                        html += '<td>' + item.internId + '</td>';
                        html += '<td>' + item.internName + '</td>';
                        html += '<td>' + item.internAddress + '</td>';
                        html += '<td>' + item.internEmail + '</td>';
                        html += '<td>' + item.internPhone + '</td>';
                        html += '<td class="text-end">' + item.university + '</td>';
                        html += '<td class="text-end">' + item.major + '</td>';
                        html += '<td class="text-end">' + item.mentorId + '</td>';
                        html += '<td><a href="#" onclick="edit(\'' + item.internId + '\')">Edit</a> | <a href="#" onclick="delele(\'' + item.internId + '\')">Delete</a></td>';

                        html += '</tr>';
                    });
                    $('.tblInterns').html(html);
                },
                error: function (xhr, error) {
                    alert(xhr.statusText);
                }
            });
        }

        function add() {
            $("#internModalContent").html("");
            $("#internModalLabel").html("Add New");

            $.ajax({
                url: '@Url.Action("Create", "InternProfiles")',
                type: "GET",
                success: function (result) {
                    $("#internModalContent").html(result);
                    $('#internModal').modal('show');
                },
                error: function (message) {
                    alert(JSON.stringify(message));
                }
            });
        }
        function edit(id) {
            $("#internModalContent").html("");
            $("#internModalLabel").html("Edit Intern Profile");

            $.ajax({
                url: '@Url.Action("Edit", "InternProfiles")',
                type: "GET",
                data: { id: id },
                success: function (result) {
                    $("#internModalContent").html(result);
                    $('#internModal').modal('show');
                },
                error: function (message) {
                    alert("An error occurred: " + message.responseText);
                }
            });
        }
/*
         function edit(id) {
                    $("#internModalContent").html("");
                    $("#internModal").html("Add New");

                    var formData = new FormData();
                    formData.append("id", id);

                    $.ajax({
                        url: '@Url.Action("Edit", "InternProfiles")',
                        type: "POST",
                        //contentType: 'application/json;charset=utf-8',
                        //dataType: "json",
                        processData: false,
                        contentType: false,
                        data: formData,
                        success: function (result) {
                            $("#topUpModalContent").html(result);
                            $('#topUpModal').modal('show');
                        },
                        error: function (message) {
                            alert(message);
                        }
                    });
                }
*/
       

        function delele(id) {
            var result = confirm("Are you sure to delete?");
            if (result) {
                //alert(id);
                var formData = new FormData();
                formData.append("id", id);

                $.ajax({
                    url: '@Url.Action("Delete", "InternProfiles")',
                    type: "DELETE",
                    //contentType: 'application/json;charset=utf-8',
                    //dataType: "json",
                    processData: false,
                    contentType: false,
                    data: formData,
                    success: function (result) {
                       
                        alert(result);
                        loadData();
                    },
                    error: function (result) {
                        alert(result);
                    }
                });
            }
        }

    </script>
}

Source/Net1711_231_5_InternManagement/InternManagementWebApp/Views/InternProfiles/_add.cshtml
@model InternManagementData.Models.InternProfile;

<div class="form-group row">
    <div class="col-md-6">
        <label for="1">Id</label>
        @* @Html.HiddenFor(model => model.ID) *@
        @Html.EditorFor(model => model.InternId, new { htmlAttributes = new { @class = "form-control" } })
        @* @Html.DropDownList("TypeCode", null, new { @class = "form-control" }) *@
    </div>
    <div class="col-m-6"/>
</div>
<div class="form-group row">
    <div class="col-md-6">
        <label for="1">Name</label>
        @Html.EditorFor(model => model.InternName, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <div class="col-md-6">
        <label for="1">Address</label>
        @Html.EditorFor(model => model.InternAddress, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <div class="col-m-6"/>
</div>

Source/Net1711_231_5_InternManagement/InternManagementWebApp/Views/InternProfiles/_edit.cshtml
@model InternManagementData.DTO.InternProfileDTO;


<div class="form-group row">
    <div class="col-md-6">
        <label for="1">ID</label>
        @Html.EditorFor(model => model.InternID, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <div class="col-md-6">
        <label hidden >Type</label>
        <input id="Type" name="Type" hidden value="edit"/>
    </div>
  

    <div class="col-m-6" />
</div>
<div class="form-group row">
    <div class="col-md-6">
        <label for="1">Name</label>
        @Html.EditorFor(model => model.InternName, new { htmlAttributes = Model.InternName })
    </div>
    <div class="col-md-6">
        <label for="1">Address</label>
        @Html.EditorFor(model => model.InternAddress, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <div class="col-m-6"/>
</div>
<div class="form-group row">
    <div class="col-md-6">
        <label for="1">Email</label>
        @Html.EditorFor(model => model.InternEmail, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <div class="col-md-6">
        <label for="1">Phone</label>
        @Html.EditorFor(model => model.InternPhone, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <div class="col-m-6" />
</div>
<div class="form-group row">
    <div class="col-md-6">
        <label for="1">University</label>
        @Html.EditorFor(model => model.University, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <div class="col-md-6">
        <label for="1">Major</label>
        @Html.EditorFor(model => model.Major, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <div class="col-m-6" />
</div>